{
 "title": "Cansat",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "300ms",
 "panels": [
  {
   "title": "Altitud",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "dataset": "cansat",
     "rawSql": "SELECT valor AS \"Metros\", hora FROM cansat.altitud ORDER BY hora "
    }
   ]
  },
  {
   "title": "Radiación",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "dataset": "cansat",
     "rawSql": "SELECT valor AS \"cpm\", hora FROM cansat.radiacion ORDER BY hora"
    }
   ]
  },
  {
   "title": "GPS",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "cansat",
     "rawSql": "SELECT latitude, longitude, hora FROM cansat.gps ORDER BY hora DESC LIMIT 1 "
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "cansat",
     "rawSql": "SELECT valor AS \"Temperatura\", hora FROM cansat.temperatura ORDER BY hora"
    }
   ]
  },
  {
   "title": "Presión atmosférica",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "dataset": "cansat",
     "rawSql": "SELECT valor AS \"Presión (hPa)\", hora FROM cansat.presion ORDER BY hora"
    }
   ]
  }
 ]
}